<?php

namespace Tests\Unit\Repositories\AccountRepositories;

use App\DTO\Accounts\UserData;
use App\Repositories\RepositoryContracts\UserRepositoryContract;
use Hash;
use Illuminate\Foundation\Testing\RefreshDatabase;
use PHPUnit\Framework\Attributes\Test;
use Tests\TestCase;

class UserRepositoryTest extends TestCase
{
    use RefreshDatabase;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    #[Test]
    public function canCreateUser(): void
    {
        $userRepository = resolve(UserRepositoryContract::class);
        $userData = new UserData(
            name: fake()->name,
            email: fake()->email
        );
        $newUser = $userRepository->createNewUser(
            userData: $userData,
            password: Hash::make(fake()->shuffleString)
        );
        $this->assertDatabaseHas(
            'users',
            ['name' => $newUser->name, 'email' => $newUser->email]
        );
    }
}
