<?php
/*
 * Copyright (c) 2026
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this
 * software and associated documentation files (the "Software"), to deal in the Software
 * without restriction, including without limitation the rights to use, copy, modify, merge,
 *  publish, distribute, sublicense, and/or sell copies of the Software, and to permit
 *  persons to whom the Software is furnished to do so, subject to the following
 *  conditions:
 *
 * The above copyright notice and this permission notice shall be included in all copies
 * or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPIRES
 * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NON INFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
declare(strict_types=1);

namespace Feature\Http\Livewire;

use App\Http\Livewire\BookmarkDialog;
use App\Models\AccountModels\User;
use App\Models\ImageModels\Bookmark;
use App\Models\ImageModels\Image;
use App\Services\ServiceContracts\ImageServiceContract;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Livewire;
use Mockery;
use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\Attributes\Test;
use Tests\TestCase;

#[CoversClass(BookmarkDialog::class)]
class BookmarkDialogTest extends TestCase
{
    use RefreshDatabase;

    private User $user;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->user = User::factory()->create();
    }

    #[Test]
    public function doesItRender(): void
    {
        Livewire::actingAs($this->user)->test(BookmarkDialog::class)
            ->assertOk()
            ->assertViewIs('livewire.bookmark-dialog');
    }

    #[Test]
    public function togglesLabelDialogWithPreset(): void
    {
        $image = Image::factory()->create();
        $mockLabel = 'My Awesome Bookmark';
        Bookmark::factory()->create(['image_id' => $image->id, 'bookmark_label' => $mockLabel]);
        $imageService = Mockery::mock(ImageServiceContract::class);
        // the method is being called directly, why is this failing expected receipts?? o.O
        $imageService->shouldReceive('getBookmarkLabel')
            ->with($image->id)
            ->andReturn($mockLabel);

        // We pass the mock service into the component
        Livewire::actingAs($this->user)->test(BookmarkDialog::class, ['imageService' => $imageService])
            ->assertSet('isBookmarkDialogOpen', false)
            ->call('editBookmarkDialogToggle', selectedThumbnail: ['id' => $image->id])
            ->assertSet('isBookmarkDialogOpen', true)
            ->assertSet('bookmarkLabel', $mockLabel);
    }

    #[Test]
    public function saveClosesTheDialog(): void
    {
        Livewire::actingAs($this->user)->test(BookmarkDialog::class)
            ->set('isBookmarkDialogOpen', true)
            ->call('saveLabel')
            ->assertSet('isBookmarkDialogOpen', false);
    }

    protected function tearDown(): void
    {
        Mockery::close();
        parent::tearDown();
    }
}
