name: Keepsake App
run-name: ${{ github.actor }} currently running Keepsake feature/unit tests
on: [ pull_request ]

jobs:
  build:
    runs-on: ubuntu-20.04

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: keepsake_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Grab current
        uses: actions/checkout@v2

      - name: Setup PHP, currently 8.3
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install deps
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Create keepsake_test db
        run: |
          PGPASSWORD=${{ secrets.KEEPSAKE_TEST_DB_PASS }} psql -h localhost -U postgres -c 'DROP DATABASE IF EXISTS keepsake_test;' && \
          PGPASSWORD=${{ secrets.KEEPSAKE_TEST_DB_PASS }} psql -h localhost -U postgres -c 'CREATE DATABASE keepsake_test;'

      - name: Prep test database
        env:
          DB_HOST: localhost
          DB_PORT: 5432
          DB_DATABASE: keepsake_test
          DB_USERNAME: ${{ secrets.KEEPSAKE_TEST_DB_USER }}
          DB_PASSWORD: ${{ secrets.KEEPSAKE_TEST_DB_PASS }}
        run: php artisan migrate --env=testing

      - name: Run test and generate coverage
        env:
          DB_HOST: localhost
          DB_PORT: 5432
          DB_DATABASE: keepsake_test
          DB_USERNAME: ${{ secrets.KEEPSAKE_TEST_DB_USERgit  }}
          DB_PASSWORD: ${{ secrets.KEEPSAKE_TEST_DB_PASS }}
        run: php artisan test --env=testing --coverage-clover=coverage.xml

      - name: Codecov
        uses: codecov/codecov-action@v4.3.0

