name: Keepsake App
run-name: ${{ github.actor }} currently running Keepsake feature/unit tests
on: [ pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: postgres
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_DB: keepsake_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Grab current
        uses: actions/checkout@v2

      - name: Setup PHP, currently 8.3
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install deps
        run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
        env:
          CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}

      - name: Create keepsake_test db
        env:
          POSTGRES_USER: postgres
        run: |
          psql -h localhost -U $POSTGRES_USER -c 'DROP DATABASE IF EXISTS keepsake_test;' && \
          psql -h localhost -U $POSTGRES_USER -c 'CREATE DATABASE keepsake_test;'

      - name: Prep test database
        env:
          DB_HOST: localhost
          DB_PORT: 5432
          DB_DATABASE: keepsake_test
          DB_USERNAME: postgres
        run: php artisan migrate --env=testing

      - name: Run test and generate coverage
        env:
          DB_HOST: localhost
          DB_PORT: 5432
          DB_DATABASE: keepsake_test
          DB_USERNAME: postgres
        run: php artisan test --env=testing --min=75 --coverage --coverage-clover=coverage.xml

      - name: Codecov
        uses: codecov/codecov-action@v4.3.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage.xml
          flags: unittests
          name: codecov-umbrella
          commit_parent: ${{ github.event.pull_request.base.sha }}

